sudo: required
services:
  - docker

before_install:
  - docker build -t aadharsharma/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run aadharsharma/react-test npm test -- --coverage

after_success:
  - docker build -t aadharsharma/multi-client ./client
  - docker build -t aadharsharma/multi-nginx ./nginx
  - docker build -t aadharsharma/multi-server ./server
  - docker build -t aadharsharma/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aadharsharma/multi-client
  - docker push aadharsharma/multi-nginx
  - docker push aadharsharma/multi-server
  - docker push aadharsharma/multi-worker

